### ISSUE TITLE
Improve documentation with screenshots and more info about the project

### ISSUE THREAD

**Issue by nikhilmufc7** [nikhilmufc7/Flutter_IeltsPrep#3]
Get infomation from here : https://play.google.com/store/apps/details?id=tech.ieltsvault.ielts and improve documentation with screenshots

**Comment by dgabriel123** [comment]
Hello @nikhilmufc7 I can begin working on this. Is there anything specific you would like me to highlight/focus on? Would you like me to just update the README?

**Comment by nikhilmufc7** [comment]
hey @dgabriel123 sure you can, anything with maybe screenshots and some basic features about the app shall work , thanks a lot!

**Comment by dgabriel123** [comment]
> hey @dgabriel123 sure you can, anything with maybe screenshots and some basic features about the app shall work , thanks a lot!

I should have a working draft tomorrow, feel free to assign the issue to me. Thanks!

**Comment by nikhilmufc7** [comment]
Thanks again @dgabriel123 for creating such great documentation for the project, really appreciate it!
